from .s01_pacman import Pacman
from .s02_init import Initialize
from .s03_network import WiFi
from .s03_network import Network
from .s04_aur import AurHelper
from .s05_bitwarden import Bitwarden
from .s06_ssh import SecureShell
from .s07_git import GitSetup
from .s08_git_repos import Git
from .s08_git_repos import Dotfiles
from .s09_install import Install
from .s10_shell import Zsh
from .s11_services import Services
from .s12_customization import Customization
from .s13_languages import Python
from .s13_languages import Ruby
